#!/bin/sh

if [ "$#" -ne 1 ]; then
  echo "Illegal number of parameters. Passed: $#.\nExpected one param: {on|off}"

elif [ "$1" == "off" ] || [ "$1" == "on" ]; then

  ./connectivity $1 1 3
  ./connectivity $1 1 4
  ./connectivity $1 1 5

  ./connectivity $1 2 3
  ./connectivity $1 2 4
  ./connectivity $1 2 5

# TODO: would be useful do describe as sets, e.g. (1 2) (3 4 5)

else
  echo "Unexpected param: $1\nExpected one param: {on|off}."

fi

