#!/bin/sh

if [ "$#" -ne 2 ]; then
  echo "Illegal number of parameters. Passed: $#.\nExpected two params: <joining-node-number> <seed-node-number>."
  exit
fi

docker-compose exec node-$1 curl -X POST -F 'address=akka.tcp://ClusterSystem@node-'$2':2552' http://node-$1:8558/cluster/members
