#!/bin/sh

if [ "$#" -ne 1 ]; then
  echo "Illegal number of parameters. Passed: $#.\nExpected one param: <application.configs.folder>."
  exit
fi

SRC_CONF=$( echo $1 | sed -e "s/^configs\///" )

ln -fs $SRC_CONF configs/application.conf

docker-compose build

docker-compose up -d

